version: '3.8'
services:
  rtsp-proxy:
    image: aler9/rtsp-simple-server
    volumes:
      - ./config.yml:/rtsp-simple-server.yml:ro
    ports:
      - "8554:8554"   # RTSP Relay
    environment:
      - RTSP_SIMPLE_SERVER_CONFIG=/rtsp-simple-server.yml

  hls-api:
    build: ./hls-api
    ports:
      - "8080:8080"
    depends_on:
      - rtsp-proxy
